# Generated by Django 4.2.11 on 2024-04-26 21:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_cons', models.DateField()),
                ('hora_cons', models.TimeField()),
                ('tipo_pag_cons', models.CharField(choices=[('Cartão', 'Cartão'), ('Dinheiro', 'Dinheiro'), ('Pix', 'Pix')], max_length=10)),
                ('status_pag_cons', models.CharField(choices=[('Pago', 'Pago'), ('Pendente', 'Pendente')], max_length=10)),
                ('status_cons', models.CharField(choices=[('Concluída', 'Concluída'), ('Cancelada', 'Cancelada'), ('Pendente', 'Pendente'), ('Remarcada', 'Remarcada')], max_length=10)),
                ('motivo', models.CharField(max_length=199)),
                ('sintomas', models.TextField(max_length=500, null=True)),
                ('observacoes', models.TextField(max_length=500, null=True)),
                ('laudo', models.TextField(max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Convenio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_carteirinha', models.IntegerField(null=True)),
                ('nome_convenio', models.CharField(max_length=50, null=True)),
                ('titular', models.CharField(max_length=50, null=True)),
                ('cpf_titular', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Receita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_rec', models.DateTimeField(auto_now_add=True)),
                ('L_esf_OD', models.CharField(max_length=30, null=True)),
                ('L_esf_OE', models.CharField(max_length=30, null=True)),
                ('L_cil_OD', models.CharField(max_length=30, null=True)),
                ('L_cil_OE', models.CharField(max_length=30, null=True)),
                ('L_eixo_OD', models.CharField(max_length=30, null=True)),
                ('L_eixo_OE', models.CharField(max_length=30, null=True)),
                ('L_dp_OD', models.CharField(max_length=30, null=True)),
                ('L_dp_OE', models.CharField(max_length=30, null=True)),
                ('P_esf_OD', models.CharField(max_length=30, null=True)),
                ('P_esf_OE', models.CharField(max_length=30, null=True)),
                ('P_cil_OD', models.CharField(max_length=30, null=True)),
                ('P_cil_OE', models.CharField(max_length=30, null=True)),
                ('P_eixo_OD', models.CharField(max_length=30, null=True)),
                ('P_eixo_OE', models.CharField(max_length=30, null=True)),
                ('P_dp_OD', models.CharField(max_length=30, null=True)),
                ('P_dp_OE', models.CharField(max_length=30, null=True)),
                ('id_consulta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paciente.consulta')),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_pac', models.CharField(max_length=30)),
                ('sobrenome_pac', models.CharField(max_length=50)),
                ('genero_pac', models.CharField(choices=[('Feminino', 'Feminino'), ('Masculino', 'Masculino')], max_length=10)),
                ('cpf_pac', models.PositiveBigIntegerField()),
                ('nasc_pac', models.DateField()),
                ('tel_pac_1', models.IntegerField()),
                ('tel_pac_2', models.IntegerField(null=True)),
                ('cep_pac', models.IntegerField()),
                ('end_pac', models.CharField(max_length=300)),
                ('bairro_pac', models.CharField(max_length=100)),
                ('cidade_pac', models.CharField(max_length=100)),
                ('email_func', models.EmailField(max_length=300)),
                ('status_cad_pac', models.BooleanField()),
                ('id_convenio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paciente.convenio')),
            ],
        ),
        migrations.CreateModel(
            name='Exame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_exame', models.CharField(max_length=30)),
                ('valor_exame', models.FloatField()),
                ('tipo_pag_ex', models.CharField(choices=[('Cartão', 'Cartão'), ('Dinheiro', 'Dinheiro'), ('Pix', 'Pix')], max_length=10)),
                ('status_pag_ex', models.CharField(choices=[('Pago', 'Pago'), ('Pendente', 'Pendente')], max_length=10)),
                ('id_consulta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paciente.consulta')),
            ],
        ),
        migrations.AddField(
            model_name='consulta',
            name='id_paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paciente.paciente'),
        ),
    ]
