# Generated by Django 4.2.11 on 2024-04-27 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consulta',
            name='id_medico',
        ),
    ]
