# Generated by Django 5.0.4 on 2024-05-13 17:47

import cpf_field.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='cpf_pac',
            field=cpf_field.models.CPFField(max_length=14, verbose_name='cpf'),
        ),
    ]
