# Generated by Django 5.0.4 on 2024-05-06 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0002_remove_consulta_id_medico'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consulta',
            name='id_paciente',
        ),
        migrations.RemoveField(
            model_name='receita',
            name='id_consulta',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='id_convenio',
        ),
        migrations.DeleteModel(
            name='Exame',
        ),
        migrations.DeleteModel(
            name='Consulta',
        ),
        migrations.DeleteModel(
            name='Receita',
        ),
        migrations.DeleteModel(
            name='Convenio',
        ),
        migrations.DeleteModel(
            name='Paciente',
        ),
    ]
