# Generated by Django 4.2.11 on 2024-05-07 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionario', '0001_initial'),
        ('paciente', '0002_remove_consulta_id_medico'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulta',
            name='id_medico',
            field=models.ManyToManyField(related_name='Consulta', to='funcionario.medico'),
        ),
    ]
