# Generated by Django 5.0.4 on 2024-05-13 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0002_alter_paciente_cpf_pac'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='cep_pac',
            field=models.CharField(max_length=30, verbose_name='CEP'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='tel_pac_1',
            field=models.CharField(max_length=30, verbose_name='Telefone 1'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='tel_pac_2',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Telefone 2 (Opcional)'),
        ),
    ]
