# Generated by Django 5.0.4 on 2024-05-13 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0003_alter_paciente_cep_pac_alter_paciente_tel_pac_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='cpf_pac',
            field=models.CharField(max_length=30, verbose_name='CPF'),
        ),
    ]
