# Generated by Django 5.0.4 on 2024-05-15 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0004_alter_paciente_cpf_pac'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='status_cad_pac',
            field=models.BooleanField(default=True, verbose_name='ativar cadastro'),
        ),
    ]
