# Generated by Django 5.0.4 on 2024-05-06 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0005_alter_paciente_status_cad_pac'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='tel_pac_2',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
