# Generated by Django 5.0.4 on 2024-05-06 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0007_alter_paciente_id_convenio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='convenio',
            name='cpf_titular',
            field=models.PositiveIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='convenio',
            name='nome_convenio',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='convenio',
            name='num_carteirinha',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='convenio',
            name='titular',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
