# Generated by Django 5.0.4 on 2024-05-06 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0008_alter_convenio_cpf_titular_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='convenio',
            name='cpf_titular',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
