# Generated by Django 5.0.4 on 2024-05-08 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0009_alter_convenio_cpf_titular'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paciente',
            old_name='email_func',
            new_name='email_pac',
        ),
    ]
