# Generated by Django 5.0.4 on 2024-05-08 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0010_rename_email_func_paciente_email_pac'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulta',
            name='laudo',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='observacoes',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='sintomas',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
