# Generated by Django 5.0.4 on 2024-05-08 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0011_alter_consulta_laudo_alter_consulta_observacoes_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='consulta',
            options={'ordering': ['data_cons', 'hora_cons']},
        ),
        migrations.AlterField(
            model_name='convenio',
            name='nome_convenio',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
