# Generated by Django 5.0.4 on 2024-05-10 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0013_remove_convenio_cpf_titular_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='status_cad_pac',
            field=models.BooleanField(verbose_name='ativar cadastro'),
        ),
    ]
