# Generated by Django 5.0.4 on 2024-05-10 18:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionario', '0006_alter_funcionario_status_cad_func'),
        ('paciente', '0014_alter_paciente_status_cad_pac'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulta',
            name='id_especialidade',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='consultas', to='funcionario.especialidade'),
        ),
    ]
