# Generated by Django 5.0.4 on 2024-05-13 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0014_alter_consulta_laudo_alter_consulta_observacoes_and_more'),
        ('paciente', '0017_alter_consulta_status_cons'),
    ]

    operations = [
    ]
