# Generated by Django 5.0.4 on 2024-05-13 22:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionario', '0006_alter_funcionario_status_cad_func'),
        ('paciente', '0017_alter_consulta_status_cons'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulta',
            name='data_cons',
            field=models.DateField(verbose_name='data'),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='hora_cons',
            field=models.TimeField(verbose_name='hora'),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='id_especialidade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultas', to='funcionario.especialidade', verbose_name='especialidade'),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='id_medico',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='Consulta', to='funcionario.medico', verbose_name='médico'),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='id_paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paciente.paciente', verbose_name='paciente'),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='laudo',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='laudo'),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='motivo',
            field=models.CharField(max_length=199, verbose_name='motivo'),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='observacoes',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='observações'),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='sintomas',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='sintomas'),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='status_cons',
            field=models.CharField(choices=[('Concluída', 'Concluída'), ('Cancelada', 'Cancelada'), ('Agendada', 'Agendada'), ('Remarcada', 'Remarcada')], max_length=10, verbose_name='Status da Consulta'),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='status_pag_cons',
            field=models.CharField(choices=[('Pago', 'Pago'), ('Pendente', 'Pendente')], max_length=10, verbose_name='Status de Pagamento'),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='tipo_pag_cons',
            field=models.CharField(choices=[('Cartão', 'Cartão'), ('Dinheiro', 'Dinheiro'), ('Pix', 'Pix')], max_length=10, verbose_name='Tipo de Pagamento'),
        ),
        migrations.AlterField(
            model_name='exame',
            name='status_pag_ex',
            field=models.CharField(choices=[('Pago', 'Pago'), ('Pendente', 'Pendente')], max_length=10, verbose_name='Status de Pagamento'),
        ),
        migrations.AlterField(
            model_name='exame',
            name='tipo_exame',
            field=models.CharField(max_length=30, verbose_name='exame'),
        ),
        migrations.AlterField(
            model_name='exame',
            name='tipo_pag_ex',
            field=models.CharField(choices=[('Cartão', 'Cartão'), ('Dinheiro', 'Dinheiro'), ('Pix', 'Pix')], max_length=10, verbose_name='Tipo de Pagamento'),
        ),
        migrations.AlterField(
            model_name='exame',
            name='valor_exame',
            field=models.FloatField(verbose_name='valor'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='num_carteirinha',
            field=models.IntegerField(blank=True, default=0, verbose_name='carteirinha'),
        ),
        migrations.AlterField(
            model_name='receita',
            name='data_rec',
            field=models.DateTimeField(auto_now_add=True, verbose_name='data'),
        ),
    ]
