# Generated by Django 4.2.11 on 2024-04-26 21:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipos_cargo', models.CharField(choices=[('Administrador(a)', 'Administrador(a)'), ('Assistente', 'Assistente'), ('Médico(a)', 'Médico(a)')], max_length=16)),
                ('nome_cargo', models.CharField(max_length=100)),
                ('descricao', models.TextField(max_length=500, null=True)),
                ('entrada', models.TimeField(null=True)),
                ('saida', models.TimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Especialidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_especialidade', models.CharField(max_length=30)),
                ('valor_consulta', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_func', models.CharField(max_length=30)),
                ('sobrenome_func', models.CharField(max_length=50)),
                ('genero_func', models.CharField(choices=[('Feminino', 'Feminino'), ('Masculino', 'Masculino')], max_length=9)),
                ('cpf_func', models.PositiveBigIntegerField()),
                ('nasc_func', models.DateField()),
                ('tel_func_1', models.IntegerField()),
                ('tel_func_2', models.IntegerField(null=True)),
                ('cep_func', models.IntegerField()),
                ('end_func', models.CharField(max_length=300)),
                ('bairro_func', models.CharField(max_length=100)),
                ('cidade_func', models.CharField(max_length=100)),
                ('email_func', models.EmailField(max_length=300)),
                ('status_cad_func', models.BooleanField()),
                ('id_cargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='funcionario.cargo')),
            ],
        ),
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnpj_med', models.CharField(max_length=12, null=True, unique=True)),
                ('crm', models.CharField(max_length=10, unique=True)),
                ('id_especialidade', models.ManyToManyField(related_name='Medicos', to='funcionario.especialidade')),
                ('id_funcionario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='funcionario.funcionario')),
            ],
        ),
    ]
