# Generated by Django 5.0.4 on 2024-04-29 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargo',
            name='nome_cargo',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='status_cad_func',
            field=models.BooleanField(verbose_name='Status de Cadastro'),
        ),
    ]
