# Generated by Django 5.0.4 on 2024-05-13 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionario', '0002_alter_funcionario_cpf_func'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='tel_func_1',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='tel_func_2',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
