# Generated by Django 5.0.4 on 2024-04-29 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionario', '0002_cargo_nome_cargo_alter_funcionario_status_cad_func'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargo',
            name='nome_cargo',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
