# Generated by Django 5.0.4 on 2024-05-06 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionario', '0003_alter_cargo_nome_cargo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargo',
            name='descricao',
            field=models.TextField(max_length=500, null=True, verbose_name='descrição'),
        ),
        migrations.AlterField(
            model_name='cargo',
            name='entrada',
            field=models.TimeField(null=True, verbose_name='entrada'),
        ),
        migrations.AlterField(
            model_name='cargo',
            name='nome_cargo',
            field=models.CharField(max_length=100, verbose_name='cargo'),
        ),
        migrations.AlterField(
            model_name='cargo',
            name='saida',
            field=models.TimeField(null=True, verbose_name='saída'),
        ),
        migrations.AlterField(
            model_name='cargo',
            name='tipos_cargo',
            field=models.CharField(choices=[('Administrador(a)', 'Administrador(a)'), ('Assistente', 'Assistente'), ('Médico(a)', 'Médico(a)')], max_length=16, verbose_name='tipo de cargo'),
        ),
        migrations.AlterField(
            model_name='especialidade',
            name='tipo_especialidade',
            field=models.CharField(max_length=30, verbose_name='especialidade'),
        ),
        migrations.AlterField(
            model_name='especialidade',
            name='valor_consulta',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='valor'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='bairro_func',
            field=models.CharField(max_length=100, verbose_name='bairro'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='cep_func',
            field=models.IntegerField(verbose_name='cep'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='cidade_func',
            field=models.CharField(max_length=100, verbose_name='cidade'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='cpf_func',
            field=models.PositiveBigIntegerField(verbose_name='cpf'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='email_func',
            field=models.EmailField(max_length=300, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='end_func',
            field=models.CharField(max_length=300, verbose_name='endereço'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='genero_func',
            field=models.CharField(choices=[('F', 'Feminino'), ('M', 'Masculino')], max_length=9, verbose_name='gênero'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='nasc_func',
            field=models.DateField(verbose_name='nascimento'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='nome_func',
            field=models.CharField(max_length=30, verbose_name='nome'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='sobrenome_func',
            field=models.CharField(max_length=50, verbose_name='sobrenome'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='status_cad_func',
            field=models.BooleanField(verbose_name='status de cadastro'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='tel_func_1',
            field=models.IntegerField(verbose_name='Telefone 1'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='tel_func_2',
            field=models.IntegerField(null=True, verbose_name='telefone 2'),
        ),
        migrations.AlterField(
            model_name='medico',
            name='cnpj_med',
            field=models.CharField(max_length=12, null=True, unique=True, verbose_name='cnpj'),
        ),
        migrations.AlterField(
            model_name='medico',
            name='crm',
            field=models.CharField(max_length=10, unique=True, verbose_name='número CRM'),
        ),
    ]
