# Generated by Django 5.0.4 on 2024-05-13 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionario', '0003_alter_funcionario_tel_func_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='cep_func',
            field=models.CharField(max_length=30),
        ),
    ]
