# Generated by Django 5.0.4 on 2024-05-13 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionario', '0004_alter_funcionario_cep_func'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='cpf_func',
            field=models.CharField(max_length=30, verbose_name='CPF'),
        ),
    ]
