# Generated by Django 5.0.4 on 2024-05-06 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionario', '0004_alter_cargo_descricao_alter_cargo_entrada_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargo',
            name='descricao',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='cargo',
            name='entrada',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='cargo',
            name='nome_cargo',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='cargo',
            name='saida',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='cargo',
            name='tipos_cargo',
            field=models.CharField(choices=[('ADM', 'Administrador(a)'), ('ATD', 'Atendente'), ('DTR', 'Médico(a)')], max_length=16),
        ),
        migrations.AlterField(
            model_name='especialidade',
            name='tipo_especialidade',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='especialidade',
            name='valor_consulta',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='bairro_func',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='cep_func',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='cidade_func',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='cpf_func',
            field=models.PositiveBigIntegerField(),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='email_func',
            field=models.EmailField(max_length=300),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='end_func',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='genero_func',
            field=models.CharField(choices=[('F', 'Feminino'), ('M', 'Masculino')], max_length=9),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='nasc_func',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='nome_func',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='sobrenome_func',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='status_cad_func',
            field=models.BooleanField(verbose_name='Ativar cadastro'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='tel_func_1',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='tel_func_2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='medico',
            name='cnpj_med',
            field=models.CharField(max_length=12, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='medico',
            name='crm',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
