# Generated by Django 5.0.4 on 2024-05-06 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionario', '0005_alter_cargo_descricao_alter_cargo_entrada_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='status_cad_func',
            field=models.BooleanField(verbose_name='Ativar Cadastro'),
        ),
    ]
