# Generated by Django 5.0.4 on 2024-05-13 22:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionario', '0006_alter_funcionario_status_cad_func'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargo',
            name='descricao',
            field=models.TextField(max_length=500, null=True, verbose_name='descrição'),
        ),
        migrations.AlterField(
            model_name='cargo',
            name='entrada',
            field=models.TimeField(null=True, verbose_name='Horário de Entrada'),
        ),
        migrations.AlterField(
            model_name='cargo',
            name='nome_cargo',
            field=models.CharField(max_length=100, verbose_name='função'),
        ),
        migrations.AlterField(
            model_name='cargo',
            name='saida',
            field=models.TimeField(null=True, verbose_name='Horário de Saída'),
        ),
        migrations.AlterField(
            model_name='cargo',
            name='tipos_cargo',
            field=models.CharField(choices=[('ADM', 'Administrador(a)'), ('ATD', 'Atendente'), ('DTR', 'Médico(a)')], max_length=16, verbose_name='Tipo de Cargo'),
        ),
        migrations.AlterField(
            model_name='especialidade',
            name='tipo_especialidade',
            field=models.CharField(max_length=30, verbose_name='especialidade'),
        ),
        migrations.AlterField(
            model_name='especialidade',
            name='valor_consulta',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='valor'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='bairro_func',
            field=models.CharField(max_length=100, verbose_name='bairro'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='cep_func',
            field=models.IntegerField(verbose_name='CEP'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='cidade_func',
            field=models.CharField(max_length=100, verbose_name='cidade'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='cpf_func',
            field=models.PositiveBigIntegerField(verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='email_func',
            field=models.EmailField(max_length=300, verbose_name='e-mail'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='end_func',
            field=models.CharField(max_length=300, verbose_name='endereço'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='genero_func',
            field=models.CharField(choices=[('F', 'Feminino'), ('M', 'Masculino')], max_length=9, verbose_name='gênero'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='id_cargo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='funcionario.cargo', verbose_name='cargo'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='nasc_func',
            field=models.DateField(verbose_name='nascimento'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='nome_func',
            field=models.CharField(max_length=30, verbose_name='nome'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='sobrenome_func',
            field=models.CharField(max_length=50, verbose_name='sobrenome'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='tel_func_1',
            field=models.IntegerField(verbose_name='telefone 1'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='tel_func_2',
            field=models.IntegerField(blank=True, null=True, verbose_name='telefone 2 (opcional)'),
        ),
        migrations.AlterField(
            model_name='medico',
            name='cnpj_med',
            field=models.CharField(max_length=12, null=True, unique=True, verbose_name='CNPJ'),
        ),
        migrations.AlterField(
            model_name='medico',
            name='crm',
            field=models.CharField(max_length=10, unique=True, verbose_name='CRM'),
        ),
        migrations.AlterField(
            model_name='medico',
            name='id_especialidade',
            field=models.ManyToManyField(related_name='Medicos', to='funcionario.especialidade', verbose_name='especialidade'),
        ),
        migrations.AlterField(
            model_name='medico',
            name='id_funcionario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='funcionario.funcionario', verbose_name='funcionário'),
        ),
    ]
