# Generated by Django 5.0.4 on 2024-05-10 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionario', '0006_alter_funcionario_status_cad_func'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargo',
            name='descricao',
            field=models.TextField(max_length=2000, null=True),
        ),
    ]
